CREATE SEQUENCE id_seq START 101;

CREATE TABLE pin_supplier (
  pinSupplierId INTEGER NOT NULL PRIMARY KEY,
  type VARCHAR(124) NOT NULL,
  subType VARCHAR(124) NOT NULL,
  name VARCHAR(124) NOT NULL,
  hardwareId VARCHAR(124) UNIQUE NOT NULL
);

